### PR TITLE
Fixing Issues in Rotate Sample Reference Frame

### LINKED ISSUE #239: Rotate Sample Reference Frame crashes for some conditions
Rotating a single slice dataset 90 degrees @ (1,0,0) crashes the filter

### PR DESCRIPTION
**Pull request by mgroeber**
Shoring up the new dimension calculations in the RotateSampleRefFrame filter.  Closes #239

### CODE REVIEW

File: Source/Plugins/ImageIO/ImageIOFilters/ImportImageStack.cpp [hunk 1]
```diff
@@ -312,6 +312,7 @@ void ImportImageStack::execute()
     // This is the first image so we need to create our block of data to store the data
     if (z ==  m_InputFileListInfo.StartIndex)
     {
+      int format = image.format();
```
Comment (imikejackson) [inline Source/Plugins/ImageIO/ImageIOFilters/ImportImageStack.cpp]: What does this change have to do with the RotateSampleRefFrame filter?

Comment (sdonegan) [inline Source/Plugins/ImageIO/ImageIOFilters/ImportImageStack.cpp]: Format looks like an unused variable
